### ISSUE TITLE
No Defined Way to Running the Project

### ISSUE THREAD

**Issue by Shub3am** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#12]
There is no script to start the project without using `node app.js` and the developer has to manually rerun the script to view the changes

**Comment by Shub3am** [comment]
Dear Maintainer. Can you add SWOC Label in this issue.
Thank You

**Comment by Shub3am** [comment]
PR Attached

**Comment by Aryainguz** [comment]
Great work @Shub3am
