### ISSUE TITLE
Bug : Standardize Promise Handling  

### ISSUE THREAD

**Issue by mathanraj0601** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#15]
## standardize Promise Handling 

```js
await sgMail
      .send(message)
      .then((response) => console.log("Email sent!"))
      .catch((error) => console.log(error.message))

    res.render("result", { pos: p, eng: e, mea: m, rel: r, acc: a 
```

In our codebase, there is a mix of using `await` and `then/catch` for handling promises. We need to standardize the approach to improve code consistency and maintainability.

### Plan:

- [x] Removing promise then/catch
- [x] Adding ' try/catch` blocks for error handling

**Comment by mathanraj0601** [comment]
I am excited to work on this @Aryainguz  Can you assign me this for SWOC24?

**Comment by Aryainguz** [comment]
Great observation and thought @mathanraj0601 go ahead and feel free to reach out for any help!

**Comment by mathanraj0601** [comment]
That's great @Aryainguz

**Comment by mathanraj0601** [comment]
Hey @Aryainguz  🌟 I've submitted a PR for the task mentioned . While diving into the issue, I spotted some opportunities to enhance the code for better readability and error handling. So, I've create  another issue or those improvements.

Could you kindly assign me to the linked issue (#29 ) ? I'm eager to kickstart the work and contribute to the project!
