### ISSUE TITLE
Adding a redirect button

### ISSUE THREAD

**Issue by maadi7** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#17]
hii @Aryainguz, we can add a redirect button at top left corner in page https://euphoria-check-perma-meter-express.vercel.app/result that will redirect users directly to home page again.

![err2](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/95737654/88770223-212f-4289-9afb-bbfdd7c87771)

**Comment by maadi7** [comment]
please assign me this under swoc.

**Comment by Aryainguz** [comment]
Go ahead @maadi7
