### ISSUE TITLE
Feature: Adding a screenshot functionality.

### ISSUE THREAD

**Issue by maadi7** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#18]
After generating results user can take a screenshot and save it on there own device by just clicking on a button. making it convienent for them to share there results with friends and family.

![err2](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/95737654/46b5ffec-7a05-4f3f-992b-a37db9ed692c)

**Comment by maadi7** [comment]
hii @Aryainguz, assign this me under SWOC.

**Comment by Aryainguz** [comment]
Great idea @maadi7 go ahead and feel free to reach out if any help needed!
