### ISSUE TITLE
Adding a middleware for validating result field values

### ISSUE THREAD

**Issue by poseidontor** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#20]
Hi @Aryainguz , I noticed that the result fields are expecting two values only (5 for frequently/affirmative and 0 for negative/rarely). But this is not being validated on the backend currently. It will be good to have a middleware validating these values.

Here I tried passing random values to the result fields and it ended up affecting the calculations.

<img width="1400" alt="Screenshot at Jan 01 11-28-44" src="https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/24155514/8dd0779c-f148-43c4-9bde-40f0af93ffa2">

**Comment by poseidontor** [comment]
@Aryainguz  If this issue is accepted, I would like to work on this for SWOC.

**Comment by Aryainguz** [comment]
Great idea to add a middleware @poseidontor go ahead and feel free to reach out in case of any help needed

**Comment by poseidontor** [comment]
@Aryainguz I noticed that the Affirmative value for the question "Do you feel a sense of purpose and direction in your life?" is 6. For rest of the questions, the accepted value is either of 5/0. Is this intensional or a bug?

https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/blob/5d04632c4de04eeb8b765def53192ad6bfe4b800/views/questions.ejs#L154C48-L154C48

If it's a bug, should I be opening a new issue or can I fix it in the PR for this one it self?

**Comment by meetjn** [comment]
Hi @Aryainguz, I would to like to contribute to this issue. Can you please assign this to me?

**Comment by meetjn** [comment]
I found a bug when I tried signing in with my email- it accepted for meet@j since I did not entered the complete email id which should be this meet@gmail.com, it accepted my email, can I create one issue like validation of email id ? or I send a pr?
