### ISSUE TITLE
Email-Id validation

### ISSUE THREAD

**Issue by meetjn** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#21]
When a new users sign-up it partially checks for the email address and lets user in and does not do complete validation like this abc@example.com
<img width="1127" alt="Screenshot 2024-01-01 at 7 30 59 PM" src="https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/141674944/6744bcf5-5a1c-48bc-95e6-9f2914e48a6e">

@Aryainguz kindly assign this issue to me so that I can fix this.

**Comment by promiseer** [comment]
correct its issue
i would like to contribute @Aryainguz please assign it to me

**Comment by promiseer** [comment]
@meetjn @Aryainguz 
issue has been fixed  here is  the [PR](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/pull/24) Link

**Comment by Aryainguz** [comment]
Solved by @promiseer
