### ISSUE TITLE
[BUG]: title on question page & result page set to default "Document"

### ISSUE THREAD

**Issue by rishita0205** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#33]
the title is not modified and  "Document" is shown on the question and result page

Steps to reproduce:
1] Submit the mail and go to Questionnaire
2] Check for the title 
3] same on the result page
 
![Screenshot 2024-01-04 155324](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/140805496/b80ab2fc-2601-4d3c-8f78-578aae41fa02)

**Comment by Nitinshukla88** [comment]
Assign this issue to me @Aryainguz

**Comment by rishita0205** [comment]
@Aryainguz  can you please add the SWOC tag also

**Comment by Aryainguz** [comment]
@rishita0205 sure added !
