### ISSUE TITLE
Screenshot not found in "CONTRIBUTING.md" file

### ISSUE THREAD

**Issue by EternoSeeker** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#35]
![Screenshot 2024-01-04 221939](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/86345498/4bfa95c5-ead9-4457-a1d0-0fa1273d23af)

**Comment by EternoSeeker** [comment]
Also screenshots can be added in readme.md file
I can work on this issue under SWOC

**Comment by Nitinshukla88** [comment]
Please assign this issue to me @Aryainguz

**Comment by Aryainguz** [comment]
@EternoSeeker you can work on this

**Comment by kamalsritha** [comment]
can you please assign me this issue under SWOC.
