### ISSUE TITLE
Improve Email Body

### ISSUE THREAD

**Issue by Aryainguz** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#4]
Email sent after user submits the questions could be improved in terms content and layout

**Comment by Muhammad-Owais-Warsi** [comment]
Hey, can i work on this issue??

**Comment by Aryainguz** [comment]
Sure @Muhammad-Owais-Warsi go ahead, try adding cool email templates and feel free to reach out for any help!

**Comment by Muhammad-Owais-Warsi** [comment]
@Aryainguz Thanks

**Comment by Muhammad-Owais-Warsi** [comment]
@Aryainguz i want some help. I tried creating my account on SendGrid to create my API Key, but  i am unable to create my account and, now i received an email stating that your account is deemed solved.

**Comment by Aryainguz** [comment]
@Muhammad-Owais-Warsi yes that’s a common issue many users face when creating account on sendgrid, try to use nodemailer it’s also a package to send emails, it’ll also send email like sendgrid api and then you can test email body

**Comment by Muhammad-Owais-Warsi** [comment]
@Aryainguz I created a pull request, it is showing all checks failed..

**Comment by Aryainguz** [comment]
Great work! @Muhammad-Owais-Warsi
