### ISSUE TITLE
Question are assigned randomly.

### ISSUE THREAD

**Issue by nepalivai** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#41]
As shown in the picture below, many questions are assigned randomly from there given number.
<img width="852" alt="image" src="https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/108126089/69cbec09-a57d-4da5-a424-f060c7118dd6">
<img width="829" alt="image" src="https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/108126089/13842278-8437-4b11-951f-93cc7e8a3035">
<img width="854" alt="image" src="https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/108126089/b3afd90d-ee08-41d3-bcb4-55504c7d383e">

**Comment by Aryainguz** [comment]
Right go ahead you can work on this @nepalivai
