### ISSUE TITLE
Add a favicon logo to Website

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#48]
Website doesn't have any favicon logo

<img width="174" alt="image" src="https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/assets/120127517/4c96c928-a1df-4705-a78f-4664cb91901d">

**Comment by Divyanshgarg-04** [comment]
@Aryainguz I would love to work on this issue

**Comment by Aryainguz** [comment]
Sure go ahead @Divyanshgarg-04
