### ISSUE TITLE
[Feature]: Include github action workflow for greeting contributors

### ISSUE THREAD

**Issue by praptisharma28** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#55]
Description:
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

Proposed Changes:
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Comment by praptisharma28** [comment]
Please assign me this @Aryainguz , will add in .github

**Comment by Aryainguz** [comment]
Sure go ahead @praptisharma28

**Comment by praptisharma28** [comment]
please add the difficulty level tag @Aryainguz

**Comment by praptisharma28** [comment]
#58 Please add the tags iwoc24 and "difficult level tag" before merging on both issue and PR thanks: ) @Aryainguz

**Comment by praptisharma28** [comment]
@Aryainguz please follow the guidelines, you should have added the difficulty level tag on both isssues and PR before merging the PR like I asked you so many times otherwise it won't count.

> #58 Please add the tags iwoc24 and "difficult level tag" before merging on both issue and PR thanks: ) @Aryainguz

**Comment by Aryainguz** [comment]
Yep sorry I’ve added them now @praptisharma28
